name: manual-job

on: workflow_dispatch

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { ref: main }
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm start
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}